# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CoreDataExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreDataExample
  pod 'RxCocoa'
  pod 'PMVP'
  pod 'PMVPCoreData', :path => '../PMVPCoreData'

  target 'CoreDataExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoreDataExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
