# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PMVPRealm' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  use_modular_headers!

  pod 'PMVP'
  pod 'RealmSwift'

end
