platform :ios, '9.0'


target 'PMVPCoreData' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'PMVP'

  target 'PMVPCoreDataTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
